-- Create the table
CREATE TABLE Countries (
    CountryId INT IDENTITY(1,1) PRIMARY KEY,
    Alpha2Code CHAR(2) NOT NULL,
    Alpha3Code CHAR(3) NOT NULL,
    NumericCode CHAR(3) NOT NULL,
    CountryName NVARCHAR(150) NOT NULL
);

-- Insert all ISO 3166-1 countries
INSERT INTO Countries (Alpha2Code, Alpha3Code, NumericCode, CountryName) VALUES
('AF', 'AFG', '004', 'Afghanistan'),
('AL', 'ALB', '008', 'Albania'),
('DZ', 'DZA', '012', 'Algeria'),
('AS', 'ASM', '016', 'American Samoa'),
('AD', 'AND', '020', 'Andorra'),
('AO', 'AGO', '024', 'Angola'),
('AI', 'AIA', '660', 'Anguilla'),
('AQ', 'ATA', '010', 'Antarctica'),
('AG', 'ATG', '028', 'Antigua and Barbuda'),
('AR', 'ARG', '032', 'Argentina'),
('AM', 'ARM', '051', 'Armenia'),
('AW', 'ABW', '533', 'Aruba'),
('AU', 'AUS', '036', 'Australia'),
('AT', 'AUT', '040', 'Austria'),
('AZ', 'AZE', '031', 'Azerbaijan'),
('BS', 'BHS', '044', 'Bahamas'),
('BH', 'BHR', '048', 'Bahrain'),
('BD', 'BGD', '050', 'Bangladesh'),
('BB', 'BRB', '052', 'Barbados'),
('BY', 'BLR', '112', 'Belarus'),
('BE', 'BEL', '056', 'Belgium'),
('BZ', 'BLZ', '084', 'Belize'),
('BJ', 'BEN', '204', 'Benin'),
('BM', 'BMU', '060', 'Bermuda'),
('BT', 'BTN', '064', 'Bhutan'),
('BO', 'BOL', '068', 'Bolivia (Plurinational State of)'),
('BQ', 'BES', '535', 'Bonaire, Sint Eustatius and Saba'),
('BA', 'BIH', '070', 'Bosnia and Herzegovina'),
('BW', 'BWA', '072', 'Botswana'),
('BR', 'BRA', '076', 'Brazil'),
('BN', 'BRN', '096', 'Brunei Darussalam'),
('BG', 'BGR', '100', 'Bulgaria'),
('BF', 'BFA', '854', 'Burkina Faso'),
('BI', 'BDI', '108', 'Burundi'),
('KH', 'KHM', '116', 'Cambodia'),
('CM', 'CMR', '120', 'Cameroon'),
('CA', 'CAN', '124', 'Canada'),
('CV', 'CPV', '132', 'Cabo Verde'),
('KY', 'CYM', '136', 'Cayman Islands'),
('CF', 'CAF', '140', 'Central African Republic'),
('TD', 'TCD', '148', 'Chad'),
('CL', 'CHL', '152', 'Chile'),
('CN', 'CHN', '156', 'China'),
('CO', 'COL', '170', 'Colombia'),
('KM', 'COM', '174', 'Comoros'),
('CG', 'COG', '178', 'Congo'),
('CD', 'COD', '180', 'Congo (Democratic Republic of the)'),
('CR', 'CRI', '188', 'Costa Rica'),
('HR', 'HRV', '191', 'Croatia'),
('CU', 'CUB', '192', 'Cuba'),
('CY', 'CYP', '196', 'Cyprus'),
('CZ', 'CZE', '203', 'Czechia'),
('DK', 'DNK', '208', 'Denmark'),
('DJ', 'DJI', '262', 'Djibouti'),
('DM', 'DMA', '212', 'Dominica'),
('DO', 'DOM', '214', 'Dominican Republic'),
('EC', 'ECU', '218', 'Ecuador'),
('EG', 'EGY', '818', 'Egypt'),
('SV', 'SLV', '222', 'El Salvador'),
('GQ', 'GNQ', '226', 'Equatorial Guinea'),
('ER', 'ERI', '232', 'Eritrea'),
('EE', 'EST', '233', 'Estonia'),
('SZ', 'SWZ', '748', 'Eswatini'),
('ET', 'ETH', '231', 'Ethiopia'),
('FJ', 'FJI', '242', 'Fiji'),
('FI', 'FIN', '246', 'Finland'),
('FR', 'FRA', '250', 'France'),
('DE', 'DEU', '276', 'Germany'),
('GH', 'GHA', '288', 'Ghana'),
('GR', 'GRC', '300', 'Greece'),
('GL', 'GRL', '304', 'Greenland'),
('GD', 'GRD', '308', 'Grenada'),
('GU', 'GUM', '316', 'Guam'),
('GT', 'GTM', '320', 'Guatemala'),
('GN', 'GIN', '324', 'Guinea'),
('GW', 'GNB', '624', 'Guinea-Bissau'),
('GY', 'GUY', '328', 'Guyana'),
('HT', 'HTI', '332', 'Haiti'),
('HN', 'HND', '340', 'Honduras'),
('HK', 'HKG', '344', 'Hong Kong'),
('HU', 'HUN', '348', 'Hungary'),
('IS', 'ISL', '352', 'Iceland'),
('IN', 'IND', '356', 'India'),
('ID', 'IDN', '360', 'Indonesia'),
('IR', 'IRN', '364', 'Iran (Islamic Republic of)'),
('IQ', 'IRQ', '368', 'Iraq'),
('IE', 'IRL', '372', 'Ireland'),
('IL', 'ISR', '376', 'Israel'),
('IT', 'ITA', '380', 'Italy'),
('JM', 'JAM', '388', 'Jamaica'),
('JP', 'JPN', '392', 'Japan'),
('JO', 'JOR', '400', 'Jordan'),
('KZ', 'KAZ', '398', 'Kazakhstan'),
('KE', 'KEN', '404', 'Kenya'),
('KR', 'KOR', '410', 'Korea, Republic of'),
('KW', 'KWT', '414', 'Kuwait'),
('KG', 'KGZ', '417', 'Kyrgyzstan'),
('LA', 'LAO', '418', 'Lao People''s Democratic Republic'),
('LV', 'LVA', '428', 'Latvia'),
('LB', 'LBN', '422', 'Lebanon'),
('LS', 'LSO', '426', 'Lesotho'),
('LR', 'LBR', '430', 'Liberia'),
('LY', 'LBY', '434', 'Libya'),
('LI', 'LIE', '438', 'Liechtenstein'),
('LT', 'LTU', '440', 'Lithuania'),
('LU', 'LUX', '442', 'Luxembourg'),
('MO', 'MAC', '446', 'Macao'),
('MG', 'MDG', '450', 'Madagascar'),
('MW', 'MWI', '454', 'Malawi'),
('MY', 'MYS', '458', 'Malaysia'),
('MV', 'MDV', '462', 'Maldives'),
('ML', 'MLI', '466', 'Mali'),
('MT', 'MLT', '470', 'Malta'),
('MX', 'MEX', '484', 'Mexico'),
('MD', 'MDA', '498', 'Moldova, Republic of'),
('MC', 'MCO', '492', 'Monaco'),
('MN', 'MNG', '496', 'Mongolia'),
('ME', 'MNE', '499', 'Montenegro'),
('MA', 'MAR', '504', 'Morocco'),
('MZ', 'MOZ', '508', 'Mozambique'),
('MM', 'MMR', '104', 'Myanmar'),
('NA', 'NAM', '516', 'Namibia'),
('NP', 'NPL', '524', 'Nepal'),
('NL', 'NLD', '528', 'Netherlands'),
('NZ', 'NZL', '554', 'New Zealand'),
('NI', 'NIC', '558', 'Nicaragua'),
('NG', 'NGA', '566', 'Nigeria'),
('NO', 'NOR', '578', 'Norway'),
('OM', 'OMN', '512', 'Oman'),
('PK', 'PAK', '586', 'Pakistan'),
('PA', 'PAN', '591', 'Panama'),
('PG', 'PNG', '598', 'Papua New Guinea'),
('PY', 'PRY', '600', 'Paraguay'),
('PE', 'PER', '604', 'Peru'),
('PH', 'PHL', '608', 'Philippines'),
('PL', 'POL', '616', 'Poland'),
('PT', 'PRT', '620', 'Portugal'),
('QA', 'QAT', '634', 'Qatar'),
('RO', 'ROU', '642', 'Romania'),
('RU', 'RUS', '643', 'Russian Federation'),
('RW', 'RWA', '646', 'Rwanda'),
('SA', 'SAU', '682', 'Saudi Arabia'),
('RS', 'SRB', '688', 'Serbia'),
('SG', 'SGP', '702', 'Singapore'),
('SK', 'SVK', '703', 'Slovakia'),
('SI', 'SVN', '705', 'Slovenia'),
('ZA', 'ZAF', '710', 'South Africa'),
('ES', 'ESP', '724', 'Spain'),
('LK', 'LKA', '144', 'Sri Lanka'),
('SE', 'SWE', '752', 'Sweden'),
('CH', 'CHE', '756', 'Switzerland'),
('TH', 'THA', '764', 'Thailand'),
('TR', 'TUR', '792', 'Türkiye'),
('UA', 'UKR', '804', 'Ukraine'),
('AE', 'ARE', '784', 'United Arab Emirates'),
('GB', 'GBR', '826', 'United Kingdom of Great Britain and Northern Ireland'),
('US', 'USA', '840', 'United States of America'),
('VN', 'VNM', '704', 'Viet Nam'),
('YE', 'YEM', '887', 'Yemen'),
('ZM', 'ZMB', '894', 'Zambia'),
('ZW', 'ZWE', '716', 'Zimbabwe');
