// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExceptionManagement.Infrastructure.Entities;

public class ExceptionLog
{
    public Guid Id { get; set; }

    public DateTime OccurredAt { get; set; }

    public string ApplicationName { get; set; }

    public string Environment { get; set; }

    public string Level { get; set; }

    public string ExceptionType { get; set; }

    public string Message { get; set; }

    public string StackTrace { get; set; }

    public string InnerException { get; set; }

    public string UserId { get; set; }

    public Guid? CorrelationId { get; set; }

    public string RequestPath { get; set; }

    public string HttpMethod { get; set; }

    public int? StatusCode { get; set; }

    public string AdditionalData { get; set; }
}