// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using ExceptionManagement.Infrastructure.Entities;
using Microsoft.EntityFrameworkCore;

namespace ExceptionManagement.Infrastructure.Data;

public partial class ExceptionsDbContext : DbContext
{
    public ExceptionsDbContext(DbContextOptions<ExceptionsDbContext> options)
        : base(options)
    {
    }



    public virtual DbSet<ExceptionLog> ExceptionLogs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ExceptionLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Exceptio__3214EC0724AB5C91");

            entity.ToTable("ExceptionLog");

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.ApplicationName).HasMaxLength(150);
            entity.Property(e => e.Environment).HasMaxLength(50);
            entity.Property(e => e.ExceptionType).HasMaxLength(300);
            entity.Property(e => e.HttpMethod).HasMaxLength(10);
            entity.Property(e => e.Level).HasMaxLength(20);
            entity.Property(e => e.OccurredAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.RequestPath).HasMaxLength(1000);
            entity.Property(e => e.UserId).HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}